### ISSUE TITLE
example does not run for me

### ISSUE THREAD

**Issue by nyck33** [flame-engine/flame#1022]
pubspec.yaml
```
name: flame_demo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flame: ^1.0.0-releasecandidate.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
code copied from https://pub.dev/packages/flame/example
```
import 'dart:math' as math;
import 'dart:ui';

import 'package:flame/anchor.dart';
import 'package:flame/gestures.dart';
import 'package:flame/components/component.dart';
import 'package:flame/components/mixins/has_game_ref.dart';
import 'package:flame/game.dart';
import 'package:flame/palette.dart';
import 'package:flutter/material.dart';

void main() {
  final game = MyGame();

  runApp(game.widget);
}

class Palette {
  static const PaletteEntry white = BasicPalette.white;
  static const PaletteEntry red = PaletteEntry(Color(0xFFFF0000));
  static const PaletteEntry blue = PaletteEntry(Color(0xFF0000FF));
}

class Square extends PositionComponent with HasGameRef<MyGame> {
  static const SPEED = 0.25;

  @override
  void render(Canvas c) {
    prepareCanvas(c);

    c.drawRect(Rect.fromLTWH(0, 0, width, height), Palette.white.paint);
    c.drawRect(const Rect.fromLTWH(0, 0, 3, 3), Palette.red.paint);
    c.drawRect(Rect.fromLTWH(width / 2, height / 2, 3, 3), Palette.blue.paint);
  }

  @override
  void update(double t) {
    super.update(t);
    angle += SPEED * t;
    angle %= 2 * math.pi;
  }

  @override
  void onMount() {
    width = height = gameRef.squareSize;
    anchor = Anchor.center;
  }
}

class MyGame extends BaseGame with DoubleTapDetector, TapDetector {
  final double squareSize = 128;
  bool running = true;

  MyGame() {
    add(Square()
      ..x = 100
      ..y = 100);
  }

  @override
  void onTapUp(details) {
    final touchArea = Rect.fromCenter(
      center: details.localPosition,
      width: 20,
      height: 20,
    );

    bool handled = false;
    components.forEach((c) {
      if (c is PositionComponent && c.toRect().overlaps(touchArea)) {
        handled = true;
        markToRemove(c);
      }
    });

    if (!handled) {
      addLater(Square()
        ..x = touchArea.left
        ..y = touchArea.top);
    }
  }

  @override
  void onDoubleTap() {
    if (running) {
      pauseEngine();
    } else {
      resumeEngine();
    }

    running = !running;
  }
}
```
I get red sqigglies under many things.
In particular the imports:
```
import 'package:flame/anchor.dart';
import 'package:flame/gestures.dart';
import 'package:flame/components/component.dart';
import 'package:flame/components/mixins/has_game_ref.dart';
```
The error message:
```
Launching lib/main.dart on 5002S in debug mode...
lib/main.dart:4:8: Error: Error when reading '/home/nobu/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flame-1.0.0-releasecandidate.15/lib/anchor.dart': No such file or directory
import 'package:flame/anchor.dart';
       ^
lib/main.dart:5:8: Error: Error when reading '/home/nobu/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flame-1.0.0-releasecandidate.15/lib/gestures.dart': No such file or directory
import 'package:flame/gestures.dart';
       ^
lib/main.dart:6:8: Error: Error when reading '/home/nobu/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flame-1.0.0-releasecandidate.15/lib/components/component.dart': No such file or directory
import 'package:flame/components/component.dart';
       ^
lib/main.dart:7:8: Error: Error when reading '/home/nobu/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flame-1.0.0-releasecandidate.15/lib/components/mixins/has_game_ref.dart': No such file or directory
import 'package:flame/components/mixins/has_game_ref.dart';
       ^
lib/main.dart:24:22: Error: Type 'PositionComponent' not found.
class Square extends PositionComponent with HasGameRef<MyGame> {
                     ^^^^^^^^^^^^^^^^^
lib/main.dart:24:45: Error: Type 'HasGameRef' not found.
class Square extends PositionComponent with HasGameRef<MyGame> {
                                            ^^^^^^^^^^
lib/main.dart:24:45: Error: Expected 0 type arguments.
class Square extends PositionComponent with HasGameRef<MyGame> {
                                            ^
lib/main.dart:50:22: Error: Type 'BaseGame' not found.
class MyGame extends BaseGame with DoubleTapDetector, TapDetector {
                     ^^^^^^^^
lib/main.dart:50:36: Error: Type 'DoubleTapDetector' not found.
class MyGame extends BaseGame with DoubleTapDetector, TapDetector {
                                   ^^^^^^^^^^^^^^^^^
lib/main.dart:50:55: Error: Type 'TapDetector' not found.
class MyGame extends BaseGame with DoubleTapDetector, TapDetector {
                                                      ^^^^^^^^^^^
lib/main.dart:24:7: Error: The type 'HasGameRef<MyGame>' can't be mixed in.
class Square extends PositionComponent with HasGameRef<MyGame> {
      ^
lib/main.dart:50:7: Error: The type 'DoubleTapDetector' can't be mixed in.
class MyGame extends BaseGame with DoubleTapDetector, TapDetector {
      ^
lib/main.dart:50:7: Error: The type 'TapDetector' can't be mixed in.
class MyGame extends BaseGame with DoubleTapDetector, TapDetector {
      ^
lib/main.dart:15:15: Error: The getter 'widget' isn't defined for the class 'MyGame'.
 - 'MyGame' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'widget'.
  runApp(game.widget);
              ^^^^^^
lib/main.dart:29:5: Error: The method 'prepareCanvas' isn't defined for the class 'Square'.
 - 'Square' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'prepareCanvas'.
    prepareCanvas(c);
    ^^^^^^^^^^^^^
lib/main.dart:31:36: Error: The getter 'width' isn't defined for the class 'Square'.
 - 'Square' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'width'.
    c.drawRect(Rect.fromLTWH(0, 0, width, height), Palette.white.paint);
                                   ^^^^^
lib/main.dart:31:43: Error: The getter 'height' isn't defined for the class 'Square'.
 - 'Square' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'height'.
    c.drawRect(Rect.fromLTWH(0, 0, width, height), Palette.white.paint);
                                          ^^^^^^
lib/main.dart:31:66: Error: The argument type 'Paint Function()' can't be assigned to the parameter type 'Paint'.
 - 'Paint' is from 'dart:ui'.
    c.drawRect(Rect.fromLTWH(0, 0, width, height), Palette.white.paint);
                                                                 ^
lib/main.dart:32:61: Error: The argument type 'Paint Function()' can't be assigned to the parameter type 'Paint'.
 - 'Paint' is from 'dart:ui'.
    c.drawRect(const Rect.fromLTWH(0, 0, 3, 3), Palette.red.paint);
                                                            ^
lib/main.dart:33:30: Error: The getter 'width' isn't defined for the class 'Square'.
 - 'Square' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'width'.
    c.drawRect(Rect.fromLTWH(width / 2, height / 2, 3, 3), Palette.blue.paint);
                             ^^^^^
lib/main.dart:33:41: Error: The getter 'height' isn't defined for the class 'Square'.
 - 'Square' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'height'.
    c.drawRect(Rect.fromLTWH(width / 2, height / 2, 3, 3), Palette.blue.paint);
                                        ^^^^^^
lib/main.dart:33:73: Error: The argument type 'Paint Function()' can't be assigned to the parameter type 'Paint'.
 - 'Paint' is from 'dart:ui'.
    c.drawRect(Rect.fromLTWH(width / 2, height / 2, 3, 3), Palette.blue.paint);
                                                                        ^
lib/main.dart:38:11: Error: Superclass has no method named 'update'.
    super.update(t);
          ^^^^^^
lib/main.dart:39:5: Error: The getter 'angle' isn't defined for the class 'Square'.
 - 'Square' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'angle'.
    angle += SPEED * t;
    ^^^^^
lib/main.dart:39:5: Error: The setter 'angle' isn't defined for the class 'Square'.
 - 'Square' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'angle'.
    angle += SPEED * t;
    ^^^^^
lib/main.dart:40:5: Error: The getter 'angle' isn't defined for the class 'Square'.
 - 'Square' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'angle'.
    angle %= 2 * math.pi;
    ^^^^^
lib/main.dart:40:5: Error: The setter 'angle' isn't defined for the class 'Square'.
 - 'Square' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'angle'.
    angle %= 2 * math.pi;
    ^^^^^
lib/main.dart:45:22: Error: The getter 'gameRef' isn't defined for the class 'Square'.
 - 'Square' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'gameRef'.
    width = height = gameRef.squareSize;
                     ^^^^^^^
lib/main.dart:45:13: Error: The setter 'height' isn't defined for the class 'Square'.
 - 'Square' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'height'.
    width = height = gameRef.squareSize;
            ^^^^^^
lib/main.dart:45:5: Error: The setter 'width' isn't defined for the class 'Square'.
 - 'Square' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'width'.
    width = height = gameRef.squareSize;
    ^^^^^
lib/main.dart:46:14: Error: The getter 'Anchor' isn't defined for the class 'Square'.
 - 'Square' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Anchor'.
    anchor = Anchor.center;
             ^^^^^^
lib/main.dart:46:5: Error: The setter 'anchor' isn't defined for the class 'Square'.
 - 'Square' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'anchor'.
    anchor = Anchor.center;
    ^^^^^^
lib/main.dart:55:5: Error: The method 'add' isn't defined for the class 'MyGame'.
 - 'MyGame' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'add'.
    add(Square()
    ^^^
lib/main.dart:56:9: Error: The setter 'x' isn't defined for the class 'Square'.
 - 'Square' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'x'.
      ..x = 100
        ^
lib/main.dart:57:9: Error: The setter 'y' isn't defined for the class 'Square'.
 - 'Square' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'y'.
      ..y = 100);
        ^
lib/main.dart:70:16: Error: 'PositionComponent' isn't a type.
      if (c is PositionComponent && c.toRect().overlaps(touchArea)) {
               ^^^^^^^^^^^^^^^^^
lib/main.dart:69:5: Error: The getter 'components' isn't defined for the class 'MyGame'.
 - 'MyGame' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'components'.
    components.forEach((c) {
    ^^^^^^^^^^
lib/main.dart:72:9: Error: The method 'markToRemove' isn't defined for the class 'MyGame'.
 - 'MyGame' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'markToRemove'.
        markToRemove(c);
        ^^^^^^^^^^^^
lib/main.dart:77:7: Error: The method 'addLater' isn't defined for the class 'MyGame'.
 - 'MyGame' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'addLater'.
      addLater(Square()
      ^^^^^^^^
lib/main.dart:78:11: Error: The setter 'x' isn't defined for the class 'Square'.
 - 'Square' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'x'.
        ..x = touchArea.left
          ^
lib/main.dart:79:11: Error: The setter 'y' isn't defined for the class 'Square'.
 - 'Square' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'y'.
        ..y = touchArea.top);
          ^
lib/main.dart:86:7: Error: The method 'pauseEngine' isn't defined for the class 'MyGame'.
 - 'MyGame' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'pauseEngine'.
      pauseEngine();
      ^^^^^^^^^^^
lib/main.dart:88:7: Error: The method 'resumeEngine' isn't defined for the class 'MyGame'.
 - 'MyGame' is from 'package:flame_demo/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'resumeEngine'.
      resumeEngine();
      ^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script '/home/nobu/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1005

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/nobu/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
Running Gradle task 'assembleDebug'...                             29.1s
Exception: Gradle task assembleDebug failed with exit code 1
```
