### ISSUE TITLE
Failed build: The return type of the method 'ComponentSet.removeAll' is 'void', which does not match the return type

### ISSUE THREAD

**Issue by bit-garden** [flame-engine/flame#1124]
Trying to get started with Flame, but no such luck. Flutter cannot build and returns error regarding an overridden function returning the wrong type.

flutter run -d windows
```
Launching lib\main.dart on Windows in debug mode...
../../../../flutter_windows_2.2.2-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flame-1.0.0-releasecandidate.16/lib/src/components/component_set.dart(132,8): error G6EB16203: The return type of the method 'ComponentSet.removeAll' is 'void', which does not match the return type, 'Iterable<Component>', of the overridden method, 'OrderedSet.removeAll'. [C:\Users\Dakun\Downloads\_stuff\code\flutter\pong\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:\Users\Dakun\Downloads\_stuff\code\flutter\pong\build\windows\CMakeFiles\d7e0bb9d83f607e3b43d14f17a30d6bb\flutter_windows.dll.rule;C:\Users\Dakun\Downloads\_stuff\code\flutter\pong\build\windows\CMakeFiles\6bc00265ba31d1f75c6be0bce11fa9b6\flutter_assemble.rule' exited with code 1. [C:\Users\Dakun\Downloads\_stuff\code\flutter\pong\build\windows\flutter\flutter_assemble.vcxproj]
Building Windows application...                                         
Exception: Build process failed.
```

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 2.6.0-11.0.pre, on Microsoft Windows [Version 10.0.19042.1288], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.2)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.62.3)
[√] Connected device (3 available)

• No issues found!
```

pubspec.yaml
```
name: pong
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flame: ^1.0.0-releasecandidate.16
  forge2d: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
```

main.dart
```
import 'package:flame/game.dart';
import 'package:flame/input.dart';
import 'package:flame/timer.dart';
import 'package:flutter/material.dart';

class TimerExample extends FlameGame with TapDetector {
  static const String description = '''
    This example shows how to use the `Timer`.\n\n
    Tap down to start the countdown timer, it will then count to 5 and then stop
    until you tap the canvas again and it restarts.
  ''';

  final TextPaint textConfig = TextPaint(
    //style: const TextStyle(color: Colors.white, fontSize: 20),
    config: TextPaintConfig(color: Colors.white, fontSize: 20.0),
  );
  late Timer countdown;
  late Timer interval;

  int elapsedSecs = 0;

  @override
  Future<void> onLoad() async {
    await super.onLoad();
    countdown = Timer(5);
    interval = Timer(
      1,
      callback: () => elapsedSecs += 1,
      repeat: true,
    );
    interval.start();
  }

  @override
  void onTapDown(_test) {
    countdown.start();
  }

  @override
  void update(double dt) {
    super.update(dt);
    countdown.update(dt);
    interval.update(dt);
  }

  @override
  void render(Canvas canvas) {
    super.render(canvas);
    textConfig.render(
      canvas,
      'Countdown: ${countdown.current.toStringAsPrecision(3)}',
      Vector2(30, 100),
    );
    textConfig.render(canvas, 'Elapsed time: $elapsedSecs', Vector2(30, 130));
  }
}
```
