### ISSUE TITLE
onCollisionEnd not getting called when collided item removed 

### ISSUE THREAD

**Issue by sahharYoucef** [flame-engine/flame#1230]
onCollisionEnd not getting called when collided item removed

**Comment by spydon** [comment]
@sahharYoucef if you want to try the fix you can depend on the PR branch.
Just put this flame entry into your pubspec.yaml file instead of the current flame entry that you have there:
```yaml
dependencies:
  flame:
    git:
      url: https://github.com/flame-engine/flame.git
      ref: spydon.collision-end-on-remove
      path: packages/flame
```
