### ISSUE TITLE
Flutter v3 throws warnings when using current version `1.1.1`

### ISSUE THREAD

**Issue by karvulf** [flame-engine/flame#1638]
# Current bug behaviour

When starting my app or tests, I always get the warning ` Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null`.

# Expected behaviour

This warning should be fixed by removing `!` or `?` after `WidgetsBinding`.

# Steps to reproduce

Update to the new flutter version `3.0.0` and start an application that uses this package.

# Flutter doctor output

```
Output of: flutter doctor -v
```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-x64, locale de-DE)
    • Flutter version 3.0.0 at /Users/andreborger/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (vor 8 Tagen), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc4)
    • Android SDK at /Users/andreborger/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 66.0.2
    • Dart plugin version 212.5744

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone SE (3rd generation) (mobile) • BE29A888-6169-45C5-9772-CB42F7342D6A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)                     • macos                                • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by karvulf** [comment]
Closing this issue because it was merged to the master. But still waiting for a release on `pub.dev`

**Comment by brenodt** [comment]
In case somebody doesn't know, here's how to use the revision of karvulf's commit until we have a new release:
```yaml
dependencies:
  flame:
    git: 
      url: https://github.com/flame-engine/flame.git
      ref: 69214827a0edb563468951256eccecab408f89df 
      path: packages/flame

# If you have other dependencies that depend themselves on flame, you can try overriding them
# Note: check what this does before using it, if you don't know --> https://dart.dev/tools/pub/dependencies#dependency-overrides
dependency_overrides:
  flame:
    git: 
      url: https://github.com/flame-engine/flame.git
      ref: 69214827a0edb563468951256eccecab408f89df 
      path: packages/flame
```
