### ISSUE TITLE
ci: Include a spell checker in the pipeline

### ISSUE THREAD

**Issue by alestiago** [flame-engine/flame#1809]
# What could be improved
Include a spell checker that automatically checks spelling for us.
This could be done by adding a github action. And a `json` file to include exceptions.

For example:
```yaml
name: spell_checker

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zwaldowski/cspell-action@v1
        with:
          paths: "**/*.{md,dart}"
          config: .github/cspell.json /// This file would include spelling exceptions
          exclude: ".gitignore"
```

# Why should this be improved
Guarantee higher quality on our code. And avoid PRs such as #1807 #1246 #1332 #1280, and so on.

# Any risks?
No risk involved. If abused, perhaps on the GitHub billing.

# More information
- https://github.com/zwaldowski/cspell-action
- https://github.com/actions/javascript-action
