### ISSUE TITLE
Bad Framerate for "Hello World" Project on Linux

### ISSUE THREAD

**Issue by michaelrampl** [flame-engine/flame#2104]
The following main.dart
```
import 'package:flame/game.dart';
import 'package:flutter/material.dart';
import 'package:mygame/mygame.dart';

void main() {
  runApp(GameWidget(game: MyGame()));
}
```
and mygame.dart
```
import 'package:flame/components.dart';
import 'package:flame/game.dart';

class MyGame extends FlameGame {
  @override
  Future<void> onLoad() async {
    add(FpsTextComponent(position: Vector2(0, 0)));
  }
}

```
only renders with about 20 FPS on my WQHD (2.560 x 1.440) Screen for both Debug and Release Builds on Linux. I'm using an NVIDIA GTX 1080 together with an i7 and 32GB of Memory. Whats interesting: If i lower the resolution (something like half of screen width/height) It goes up to around 59/60 FPS. The weird thing is that neither system monitors show a high load in cpu/gpu or memory nor does the flutter performance view show anything special. 
![image](https://user-images.githubusercontent.com/60225162/197258967-e22ee682-3e4b-4717-b57d-06dae0f60fbe.png)

Flutter doctor output
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on openSUSE Tumbleweed 5.19.13-1-default, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.1)
[✓] Android Studio
[✓] VS Code (version 1.71.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

pubspec.yaml
```
name: mygame
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
```

If I had to guess I would say that there might be some kind of resource limitation on linux to the skia/canvas but as mentioned this is only a vague guess.
