### ISSUE TITLE
Import SVG as string

### ISSUE THREAD

**Issue by CristovoXDGM** [flame-engine/flame#3029]
# Problem to solve
Currently in flutter we have a option to import SVG files with flutter_svg as String, this is good when we need to customize the SVG color, at flame_svg we dont have that yet

# Proposal
Would be good to have this for flame_svg, so we can be able to custom SVG colors from code, this helps a lot to create a color switch for the asset.

# More information

Example of what we can do with the current flutter_svg
```
Future<String> loadAssetWithColorReplaced(
    String assetPath,
    CarColorParams params,
  ) async {
    final svg = await rootBundle.loadString(assetPath);

    var assetWithColorReplaced = svg.replaceAll("#F93228", params.pureColor);

    return assetWithColorReplaced;
  }
```

@spydon

**Comment by spydon** [comment]
Hey @CristovoXDGM,
I implemented a string loader in `Svg`, you can try it by depending on the PR branch:
```yaml
dependencies:
  flame:
    git:
      url: https://github.com/flame-engine/flame.git
      ref: feat/add-svg-string-loading
      path: packages/flame
```

**Comment by CristovoXDGM** [comment]
I will test it here, btw, thanks for that man @spydon , you`re the best

**Comment by CristovoXDGM** [comment]
@spydon Got this error 
![image](https://github.com/flame-engine/flame/assets/13990822/886e2e94-4b90-4fa3-a9b7-555454600794)

**Comment by CristovoXDGM** [comment]
I have run into an error, it is saying that depends on flame_svg package @spydon

**Comment by spydon** [comment]
Ah right, forgot that the change isn't in the core package, then you have to do this:
```yaml
dependencies:
  flame_svg:
    git:
      url: https://github.com/flame-engine/flame.git
      ref: feat/add-svg-string-loading
      path: packages/flame_svg

dependency_overrides:
  flame:
    git:
      url: https://github.com/flame-engine/flame.git
      ref: feat/add-svg-string-loading
      path: packages/flame
```
