### ISSUE TITLE
lookAt() does not account for negative scale values

### ISSUE THREAD

**Issue by gnarhard** [flame-engine/flame#3625]
### What happened?

the method 'lookAt()' will not look at the correct target vector if the parent's scale is negative.

### What do you expect?

lookAt() should check for the component's scale while calculating its angle.

### Relevant log output

```shell

```

### Execute in a terminal and put output into the code block below

Output of: flutter doctor -v

### Affected platforms

All

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by spydon** [comment]
Can you try this branch (I haven't had time to try it yet):
```yaml
dependency_overrides:
  flame:
    git:
      url: https://github.com/flame-engine/flame.git
      ref: fix/look-at-to-take-scale-into-consideration
      path: packages/flame
```
