### ISSUE TITLE
Rework the examples deploy github action

### ISSUE THREAD

**Issue by luanpotter** [flame-engine/flame#703]
Previously on our `flame_examples` repo we had this action:

```
name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - uses: erickzanardo/flutter-gh-pages@v2
        with:
          useCanvasKit: true
```

We need to not only add `workingDir: 'example'`, move it to this repo and make sure it works with our new structure/flutter 2/etc. @erickzanardo shall take a look at this.

**Comment by erickzanardo** [comment]
@luanpotter I have fixed the action, here is the new code that you can use on the action

```yml

name: Gh-Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: erickzanardo/flutter-gh-pages@v3
        with:
          workingDir: example
          webRenderer: canvaskit
```
